<a href="https://colab.research.google.com/github/MahamShafiq/Numpy/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics
This notebook covers some of the basic functions of numpy,Moreover it has the solution of Deep Learning Nanodegree Numpy quiz udacity

In [0]:

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])


In [0]:
c=np.column_stack((a,b))
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
c=np.row_stack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
j=np.hstack((a,b))
j

array([1, 2, 3, 4, 5, 6])

In [0]:
j=np.vstack((a,b))
j

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
j=np.dstack((a,b))
j

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [0]:
c.flatten()
a,b=c.shape
b


(2, 3)

In [0]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [0]:
np.split(d,[2,3])

[array([1, 2]), array([3]), array([4, 5, 6])]

In [0]:
np.tile(d,2)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [0]:
np.repeat(d,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [0]:
d[2:4:2]

array([3])

In [0]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array-np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min/np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    a,b=m1.shape
    c,d=m2.shape
    if b!=c and a!=d:
        return False
    
    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if(b==c): return np.matmul(m1,m2)
    elif(a==d): return np.matmul(m2,m1) 
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.average(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
